version: '2.3'

volumes:
   restapi_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/db


services:
  db:
    image: postgres:latest
    restart: always
    env_file: 
      - .env
    volumes:
      - restapi_db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 7
      start_period: 15s

  

  backend:
    build: 
      context: ./src/
    restart: always
    env_file: 
      - .env
    ports:
      - ${PORT}:8000
    depends_on:
      db:
        condition: service_healthy